=== Sage-Bionetworks/data_curator_config/schemas/dca_config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "dca-dcc-config",
  "title": "Configuration for individual DCCs in mtDCA",
  "description": "Configuration options for a specific DCC in mtDCA",
  "requires": [ "project_name", "synapse_asset_view", "data_model_url", "template_menu_config_file" ],
  "properties": {
    "project_name": {
      "description": "Name of the DCC",
      "type": "string"
    },
    "synapse_asset_view": {
      "description": "Synapse ID of the DCC's main asset view",
      "type": "string"
    },
    "data_model_url": {
      "description": "URL to the DCC's data model",
      "type": "string"
    },
    "data_model_info": {
      "description": "URL to release notes about the data model",
      "type": "string"
    },
    "template_menu_config_file": {
      "description": "URL to the template dropdown menu config",
      "type": "string"
    },
    "logo_location": {
      "description": "URL to the DCC's logo",
      "type": "string"
    },
    "logo_link": {
      "description": "Link for the DCC",
      "type": "string"
    },
    "dcc_help_link": {
      "description": "URL DCC users can seek help",
      "type": "string"
    },
    "manifest_output_format": {
      "description": "Output type for downloaded manifests. excel or google_sheet",
      "type": "string"
    },
    "manifest_use_annotations": {
      "description": "Schematic manifest get option",
      "type": "boolean"
    },
    "validate_restrict_rules": {
      "description": "Schematic model validate option",
      "type": "boolean"
    },
    "submit_use_schema_labels": {
      "description": "Schematic model submit option",
      "type": "boolean"
    },
    "submit_table_manipulation": {
      "description": "Schematic model submit option",
      "type": "string"
    },
    "submit_manifest_record_type": {
      "description": "Schematic model submit option",
      "type": "string"
    },
    "submit_hide_blanks": {
      "description": "Schematic model submit option",
      "type": "boolean"
    },
    "use_compliance_dashboard": {
      "description": "Display the compliance dashboard. Unavaible at the moment",
      "type": "boolean"
    },
    "primary_col": {
      "description": "center header color hex code",
      "type": "string"
    },
    "secondary_col": {
      "description": "right header color hex code",
      "type": "string"
    },
    "sidebar_col": {
      "description": "left header color hex code",
      "type": "string"
    }
  }
}

=== Sage-Bionetworks/data_curator_config/dcc/HTAN/htan_dca_config.json
{
  "project_name":"HTAN All Projects",
  "synapse_asset_view":"syn20446927",
  "data_model_url":"https://raw.githubusercontent.com/ncihtan/data-models/main/HTAN.model.jsonld",
  "template_menu_config_file":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/HTAN/dca-template-config.json",
  "logo_location":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/HTAN/HTAN_text_logo.png",
  "logo_link":"https://humantumoratlas.org",
  "manifest_output_format":"google_sheet",
  "manifest_use_annotations":false,
  "validate_restrict_rules":false,
  "submit_use_schema_labels":true,
  "submit_table_manipulation":"replace",
  "submit_manifest_record_type":"file_only",
  "submit_hide_blanks":false,
  "use_compliance_dashboard":false,
  "primary_col":"#605ca8",
  "secondary_col":"#5F008C",
  "sidebar_col":"#191919"
}

=== Sage-Bionetworks/data_curator_config/dcc/ADKP/adkp_dca_config.json
[{"project_name":"AD Knowledge Portal","synapse_asset_view":"syn51324810","data_model_url":"https://raw.githubusercontent.com/adknowledgeportal/data-models/main/divco.data.model.v1.jsonld","template_menu_config_file":"ADKP/dca-template-config.json","logo_location":"ADKP/ADKnowledgePortal.png","logo_link":"https://adknowledgeportal.synapse.org","manifest_output_format":"excel","manifest_use_annotations":false,"validate_restrict_rules":false,"submit_use_schema_labels":true,"submit_table_manipulation":"replace","submit_manifest_record_type":"file_only","submit_hide_blanks":false,"use_compliance_dashboard":false,"primary_col":"#2a668d","secondary_col":"#184e71","sidebar_col":"#191919"}]

=== Sage-Bionetworks/data_curator_config/dcc/VEOIBD/veoibd_dca_config.json
{
  "project_name":"VEOIBD",
  "synapse_asset_view":"syn51397378",
  "data_model_url":"https://raw.githubusercontent.com/VEOIBD/data_models/main/veoibd.data.model.jsonld",
  "template_menu_config_file":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/VEOIBD/dca-template-config.json",
  "logo_location":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/VEOIBD/VEOIBD Logo.png",
  "logo_link":"https://veoibd.org",
  "manifest_output_format":"excel",
  "manifest_use_annotations":false,
  "validate_restrict_rules":true,
  "submit_use_schema_labels":true,
  "submit_table_manipulation":"upsert",
  "submit_manifest_record_type":"file_only",
  "submit_hide_blanks":false,
  "use_compliance_dashboard":false,
  "primary_col":"#2a668d",
  "secondary_col":"#184e72",
  "sidebar_col":"#191920"
}

=== Sage-Bionetworks/data_curator_config/test/test_no_project_permission_dca_config.json
{"project_name":"DCA Test No Project Permission","synapse_asset_view":"syn52579642","data_model_url":"https://raw.githubusercontent.com/Sage-Bionetworks/data-models/main/example.model.jsonld","template_menu_config_file":"dcc/demo/dca-template-config.json","logo_location":"dcc/demo/Logo_Sage_Logomark.png","logo_link":"https://synapse.org","manifest_output_format":"google_sheet","manifest_use_annotations":false,"validate_restrict_rules":false,"submit_use_schema_labels":true,"submit_table_manipulation":"replace","submit_manifest_record_type":"table_and_file","submit_hide_blanks":false,"use_compliance_dashboard":false,"primary_col":"#2a668d","secondary_col":"#184e71","sidebar_col":"#191919"}

=== Sage-Bionetworks/data_curator_config/dcc/GF/gf_dca_config.json
{
  "project_name":"Gray Foundation",
  "synapse_asset_view":"syn28142805",
  "data_model_url":"https://raw.githubusercontent.com/gf-dcc/data-model/v1.1.0-rc/GF.jsonld",
  "template_menu_config_file":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/GF/dca-template-config.json",
  "manifest_output_format":"google_sheet",
  "manifest_use_annotations":false,
  "validate_restrict_rules":true,
  "submit_use_schema_labels":true,
  "submit_table_manipulation":"replace",
  "submit_manifest_record_type":"table_only",
  "submit_hide_blanks":false,
  "use_compliance_dashboard":false,
  "primary_col":"#2a668d",
  "secondary_col":"#184e71",
  "sidebar_col":"#191919"
}

=== Sage-Bionetworks/data_curator_config/dcc/NF-OSI/nf-osi_dca_config.json
{
  "project_name":"NF-OSI",
  "synapse_asset_view":"syn16858331",
  "data_model_url":"https://raw.githubusercontent.com/nf-osi/nf-metadata-dictionary/v8.0.1/NF.jsonld",
  "template_menu_config_file":"dcc/NF-OSI/dca-template-config.json",
  "manifest_output_format":"google_sheet",
  "manifest_use_annotations":true,
  "validate_restrict_rules":false,
  "submit_use_schema_labels":true,
  "submit_table_manipulation":"replace",
  "submit_manifest_record_type":"table_and_file",
  "submit_hide_blanks":true,
  "use_compliance_dashboard":false,
  "primary_col":"#2a668d",
  "secondary_col":"#184e71",
  "sidebar_col":"#191919"
}

=== Sage-Bionetworks/data_curator_config/dcc/EL/el_dca_config.json
{
  "project_name":"EL",
  "synapse_asset_view":"syn51753858",
  "data_model_url":"https://raw.githubusercontent.com/Sage-Bionetworks/ELITE-data-models/main/example.model.jsonld",
  "template_menu_config_file":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/EL/dca-template-config.json",
  "manifest_output_format":"excel",
  "manifest_use_annotations":false,
  "validate_restrict_rules":false,
  "submit_use_schema_labels":true,
  "submit_table_manipulation":"replace",
  "submit_manifest_record_type":"table_and_file",
  "submit_hide_blanks":false,
  "use_compliance_dashboard":false,
  "primary_col":"#2a668d",
  "secondary_col":"#184e71",
  "sidebar_col":"#191919"
}

=== Sage-Bionetworks/data_curator_config/dcc/BTC/btc_dca_config.json
[{"project_name":"BTC DCC","synapse_asset_view":"syn51407795","data_model_url":"https://raw.githubusercontent.com/Sage-Bionetworks/btc-data-models/main/btc.model.jsonld","template_menu_config_file":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/BTC/dca-template-config.json","manifest_output_format":"excel","manifest_use_annotations":false,"validate_restrict_rules":false,"submit_use_schema_labels":true,"submit_table_manipulation":"replace","submit_manifest_record_type":"table_and_file","submit_hide_blanks":false,"use_compliance_dashboard":false,"primary_col":"#2a668d","secondary_col":"#184e72","sidebar_col":"#191920"}]
