=== Sage-Bionetworks/data_curator_config/schemas/dca_config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "dca-dcc-config",
  "title": "Configuration for individual DCCs in mtDCA",
  "description": "Configuration options for a specific DCC in mtDCA",
  "requires": [ "project_name", "synapse_asset_view", "data_model_url", "template_menu_config_file" ],
  "properties": {
    "project_name": {
      "description": "Name of the DCC",
      "type": "string"
    },
    "synapse_asset_view": {
      "description": "Synapse ID of the DCC's main asset view",
      "type": "string"
    },
    "data_model_url": {
      "description": "URL to the DCC's data model",
      "type": "string"
    },
    "data_model_info": {
      "description": "URL to release notes about the data model",
      "type": "string"
    },
    "template_menu_config_file": {
      "description": "URL to the template dropdown menu config",
      "type": "string"
    },
    "logo_location": {
      "description": "URL to the DCC's logo",
      "type": "string"
    },
    "logo_link": {
      "description": "Link for the DCC",
      "type": "string"
    },
    "dcc_help_link": {
      "description": "URL DCC users can seek help",
      "type": "string"
    },
    "manifest_output_format": {
      "description": "Output type for downloaded manifests. excel or google_sheet",
      "type": "string"
    },
    "manifest_use_annotations": {
      "description": "Schematic manifest get option",
      "type": "boolean"
    },
    "validate_restrict_rules": {
      "description": "Schematic model validate option",
      "type": "boolean"
    },
    "submit_use_schema_labels": {
      "description": "Schematic model submit option",
      "type": "boolean"
    },
    "submit_table_manipulation": {
      "description": "Schematic model submit option",
      "type": "string"
    },
    "submit_manifest_record_type": {
      "description": "Schematic model submit option",
      "type": "string"
    },
    "submit_hide_blanks": {
      "description": "Schematic model submit option",
      "type": "boolean"
    },
    "use_compliance_dashboard": {
      "description": "Display the compliance dashboard. Unavaible at the moment",
      "type": "boolean"
    },
    "primary_col": {
      "description": "center header color hex code",
      "type": "string"
    },
    "secondary_col": {
      "description": "right header color hex code",
      "type": "string"
    },
    "sidebar_col": {
      "description": "left header color hex code",
      "type": "string"
    }
  }
}

=== Sage-Bionetworks/data_curator_config/dcc/MC2/mc2_dca_config.json
[{"project_name":"Cancer Complexity Knowledge Portal - Database","synapse_asset_view":"syn27210848","data_model_url":"https://raw.githubusercontent.com/mc2-center/data-models/main/mc2.model.jsonld","template_menu_config_file":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/MC2/dca-template-config.json","logo_location":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/MC2/cckp_logo.png","logo_link":"https://cancercomplexity.synapse.org","manifest_output_format":"excel","manifest_use_annotations":false,"validate_restrict_rules":false,"submit_use_schema_labels":false,"submit_table_manipulation":"upsert","submit_manifest_record_type":"table_and_file","submit_hide_blanks":false,"use_compliance_dashboard":false,"primary_col":"#407BA0","secondary_col":"#5BB0B5","sidebar_col":"#191919"}]

=== Sage-Bionetworks/data_curator_config/dcc/demo/dca_demo_dca_config.json
{
  "project_name":"DCA Demo",
  "synapse_asset_view":"syn33715412",
  "data_model_url":"https://raw.githubusercontent.com/Sage-Bionetworks/data-models/main/example.model.jsonld",
  "data_model_info": "",
  "template_menu_config_file":"demo/dca-template-config.json",
  "logo_location":"demo/Logo_Sage_Logomark.png",
  "logo_link":"https://synapse.org",
  "dcc_help_link": "",
  "manifest_output_format":"google_sheet",
  "manifest_use_annotations":false,
  "validate_restrict_rules":false,
  "submit_use_schema_labels":true,
  "submit_table_manipulation":"replace",
  "submit_manifest_record_type":"table_and_file",
  "submit_hide_blanks":false,
  "use_compliance_dashboard":false,
  "primary_col":"#2a668d",
  "secondary_col":"#184e71",
  "sidebar_col":"#191919"
}

=== Sage-Bionetworks/data_curator_config/dcc/demo_upsert/demo_upsert_dca_config.json
{
  "project_name":"DCA Demo Upsert",
  "synapse_asset_view":"syn51489635",
  "data_model_url":"https://raw.githubusercontent.com/Sage-Bionetworks/schematic/develop/tests/data/example.model.jsonld",
  "template_menu_config_file":"https://raw.githubusercontent.com/Sage-Bionetworks/data_curator_config/config-refactor/dcc/demo_upsert/dca-template-config.json",
  "manifest_output_format":"excel",
  "manifest_use_annotations":false,
  "validate_restrict_rules":false,
  "submit_use_schema_labels":false,
  "submit_table_manipulation":"upsert",
  "submit_manifest_record_type":"table_and_file",
  "submit_hide_blanks":false,
  "use_compliance_dashboard":false,
  "primary_col":"#2a668d",
  "secondary_col":"#184e71",
  "sidebar_col":"#191919"
}
